package com.davygeeroms.dartsgames.enums

enum class BoardValues(val valuesStr: String) {
    S20("Twenty"),
    D20("Double Twenty"),
    T20("Triple Twenty"),
    S19("Nineteen"),
    D19("Double Nineteen"),
    T19("Triple Nineteen"),
    S18("Eighteen"),
    D18("Double Eighteen"),
    T18("Triple Eighteen"),
    S17("Seventeen"),
    D17("Double Seventeen"),
    T17("Triple Seventeen"),
    S16("Sixteen"),
    D16("Double Sixteen"),
    T16("Triple Sixteen"),
    S15("Fifteen"),
    D15("Double Fifteen"),
    T15("Triple Fifteen"),
    S14("Fourteen"),
    D14("Double Fourteen"),
    T14("Triple Fourteen"),
    S13("Thirteen"),
    D13("Double Thirteen"),
    T13("Triple Thirteen"),
    S12("Twelve"),
    D12("Double Twelve"),
    T12("Triple Twelve"),
    S11("Eleven"),
    D11("Double Eleven"),
    T11("Triple Eleven"),
    S10("Ten"),
    D10("Double Ten"),
    T10("Triple Ten"),
    S9("Nine"),
    D9("Double Nine"),
    T9("Triple Nine"),
    S8("Eight"),
    D8("Double Eight"),
    T8("Triple Eight"),
    S7("Seven"),
    D7("Double Seven"),
    T7("Triple Seven"),
    S6("Six"),
    D6("Double Six"),
    T6("Triple Six"),
    S5("Five"),
    D5("Double Five"),
    T5("Triple Five"),
    S4("Four"),
    D4("Double Four"),
    T4("Triple Four"),
    S3("Three"),
    D3("Double Three"),
    T3("Triple Three"),
    S2("Two"),
    D2("Double Two"),
    T2("Triple Two"),
    S1("One"),
    D1("Double One"),
    T1("Triple One"),
    S25("Bull"),
    D25("Bullseye")

}